apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: react-deploy
  name: react-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-deploy
  template:
    metadata:
      labels:
        app: react-deploy
    spec:
      containers:
      - image: cloudnice/react-image-kubernetes-todos
        name: react
        ports:
        - containerPort: 3000
        resources: {}